openapi: 3.0.0
info:
  title: Event Posters API
  version: 1.0.0
  description: API for managing event posters
paths:
  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register"

  /events:
    get:
      $ref: "./endpoints/posters.yaml#/getAllEvents"

    post:
      $ref: "./endpoints/posters.yaml#/createEvent"

  /events/{eventId}:
    get:
      $ref: "./endpoints/posters.yaml#/getEvent"

    delete:
      $ref: "./endpoints/posters.yaml#/deleteEvent"
